import { PlantCatalogEntry, Plant, PlantCategory } from './types';
import { addDays, format } from 'date-fns';

export const OPEN_METEO_URL =
  'https://api.open-meteo.com/v1/forecast?latitude=43.083&longitude=-2.406&current=temperature_2m,weathercode,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max&timezone=Europe/Madrid&forecast_days=7';

export const PLANT_CATALOG: Record<PlantCategory, PlantCatalogEntry> = {
  tomate: {
    category: 'tomate',
    displayName: 'Tomate',
    icon: '🍅',
    harvestDaysMin: 110,
    harvestDaysMax: 150,
    frostSensitive: true,
    minGerminationTempC: 18,
    wateringFrequencyDays: { dry: 2, normal: 3, wet: 5 },
    claySoilNotes:
      'Suelo arcilloso: asegúrate de un buen drenaje. Añade perlita o arena gruesa si hay encharcamiento.',
  },
  fresa: {
    category: 'fresa',
    displayName: 'Fresa',
    icon: '🍓',
    harvestDaysMin: 45,
    harvestDaysMax: 75,
    frostSensitive: false,
    minGerminationTempC: null,
    wateringFrequencyDays: { dry: 2, normal: 2, wet: 4 },
    claySoilNotes:
      'Suelo arcilloso: riesgo de pudrición de raíz. Planta en montículo elevado y evita el riego excesivo.',
  },
  ajo: {
    category: 'ajo',
    displayName: 'Ajo',
    icon: '🧄',
    harvestDaysMin: 90,
    harvestDaysMax: 120,
    frostSensitive: false,
    minGerminationTempC: 5,
    wateringFrequencyDays: { dry: 5, normal: 7, wet: 10 },
    claySoilNotes:
      'Suelo arcilloso: puede dificultar el desarrollo del bulbo. Afloja bien el suelo en profundidad antes de plantar.',
  },
  acelga: {
    category: 'acelga',
    displayName: 'Acelga',
    icon: '🥬',
    harvestDaysMin: 55,
    harvestDaysMax: 90,
    frostSensitive: false,
    minGerminationTempC: 10,
    wateringFrequencyDays: { dry: 2, normal: 3, wet: 5 },
    claySoilNotes: null,
  },
  zanahoria: {
    category: 'zanahoria',
    displayName: 'Zanahoria',
    icon: '🥕',
    harvestDaysMin: 90,
    harvestDaysMax: 120,
    frostSensitive: false,
    minGerminationTempC: 7,
    wateringFrequencyDays: { dry: 3, normal: 4, wet: 6 },
    claySoilNotes:
      'Suelo arcilloso: MUY IMPORTANTE aflojar el suelo al menos 30cm de profundidad. La arcilla causa zanahorias deformadas y bifurcadas.',
  },
  perejil: {
    category: 'perejil',
    displayName: 'Perejil',
    icon: '🌿',
    harvestDaysMin: 70,
    harvestDaysMax: 90,
    frostSensitive: false,
    minGerminationTempC: 10,
    wateringFrequencyDays: { dry: 2, normal: 3, wet: 5 },
    claySoilNotes: null,
  },
  pimiento: {
    category: 'pimiento',
    displayName: 'Pimiento',
    icon: '🫑',
    harvestDaysMin: 75,
    harvestDaysMax: 100,
    frostSensitive: true,
    minGerminationTempC: 20,
    wateringFrequencyDays: { dry: 2, normal: 3, wet: 5 },
    claySoilNotes:
      'Suelo arcilloso: asegura buen drenaje. El pimiento es muy sensible a la asfixia radicular.',
  },
  lechuga: {
    category: 'lechuga',
    displayName: 'Lechuga',
    icon: '🥗',
    harvestDaysMin: 40,
    harvestDaysMax: 55,
    frostSensitive: false,
    minGerminationTempC: 7,
    wateringFrequencyDays: { dry: 2, normal: 2, wet: 4 },
    claySoilNotes:
      'Suelo arcilloso: la lechuga puede tolerar bien el suelo pesado si no hay encharcamiento.',
  },
  puerro: {
    category: 'puerro',
    displayName: 'Puerro',
    icon: '🌱',
    harvestDaysMin: 120,
    harvestDaysMax: 150,
    frostSensitive: false,
    minGerminationTempC: 7,
    wateringFrequencyDays: { dry: 3, normal: 4, wet: 7 },
    claySoilNotes:
      'Suelo arcilloso: el puerro se adapta bien, pero asegúrate de que no se encharca. Aporcar bien para blanquear el tallo.',
  },
  cebolla: {
    category: 'cebolla',
    displayName: 'Cebolla',
    icon: '🧅',
    harvestDaysMin: 80,
    harvestDaysMax: 100,
    frostSensitive: false,
    minGerminationTempC: 10,
    wateringFrequencyDays: { dry: 4, normal: 5, wet: 8 },
    claySoilNotes:
      'Suelo arcilloso: riesgo de pudrición del bulbo por exceso de humedad. Mejora el drenaje con arena o perlita.',
  },
  otro: {
    category: 'otro',
    displayName: 'Otro',
    icon: '🌱',
    harvestDaysMin: 60,
    harvestDaysMax: 120,
    frostSensitive: false,
    minGerminationTempC: null,
    wateringFrequencyDays: { dry: 3, normal: 4, wet: 6 },
    claySoilNotes: null,
  },
};

// ---------------------------------------------------------------------------
// Helpers para seed data
// ---------------------------------------------------------------------------

function harvest(plantedAt: string, daysMin: number, daysMax: number) {
  const base = new Date(plantedAt);
  return {
    harvestWindowStart: format(addDays(base, daysMin), 'yyyy-MM-dd'),
    harvestWindowEnd: format(addDays(base, daysMax), 'yyyy-MM-dd'),
  };
}

const D1 = '2026-04-08'; // siembra original
const D2 = '2026-04-18'; // nueva siembra (sábado 18 abril)

export const INITIAL_PLANTS: Plant[] = [
  // ── Lote 1: plantado el 8 de abril ──────────────────────────────────────
  {
    id: 'plant-001',
    name: 'Tomate comprado',
    category: 'tomate',
    origin: 'comprada',
    plantedAt: D1,
    heightCm: 20,
    quantity: 1,
    bedNumber: 1,
    soilType: 'jardin_arcilloso',
    notes: 'Planta comprada en vivero, 20 cm al trasplante.',
    ...harvest(D1, 110, 150),
    updatedAt: D1,
  },
  {
    id: 'plant-002',
    name: 'Tomate germinado',
    category: 'tomate',
    origin: 'autogerminated',
    plantedAt: D1,
    heightCm: 4,
    quantity: 1,
    bedNumber: 1,
    soilType: 'jardin_arcilloso',
    notes: 'Germinada en casa, 4 cm al trasplante.',
    ...harvest(D1, 130, 170),
    updatedAt: D1,
  },
  {
    id: 'plant-003',
    name: 'Fresas (8 abr)',
    category: 'fresa',
    origin: 'comprada',
    plantedAt: D1,
    heightCm: 5,
    quantity: 1,
    bedNumber: 2,
    soilType: 'jardin_arcilloso',
    notes: 'Plantas de fresa de vivero, 5 cm.',
    ...harvest(D1, 45, 75),
    updatedAt: D1,
  },
  {
    id: 'plant-004',
    name: 'Ajo germinado',
    category: 'ajo',
    origin: 'autogerminated',
    plantedAt: D1,
    heightCm: 4,
    quantity: 1,
    bedNumber: 2,
    soilType: 'jardin_arcilloso',
    notes: 'Diente de ajo germinado en casa, 4 cm.',
    ...harvest(D1, 90, 120),
    updatedAt: D1,
  },
  {
    id: 'plant-005',
    name: 'Acelga',
    category: 'acelga',
    origin: 'siembra_directa',
    plantedAt: D1,
    heightCm: null,
    quantity: 1,
    bedNumber: 3,
    soilType: 'jardin_arcilloso',
    notes: 'Sembrada directamente.',
    ...harvest(D1, 55, 90),
    updatedAt: D1,
  },
  {
    id: 'plant-006',
    name: 'Zanahoria',
    category: 'zanahoria',
    origin: 'siembra_directa',
    plantedAt: D1,
    heightCm: null,
    quantity: 1,
    bedNumber: 3,
    soilType: 'jardin_arcilloso',
    notes: 'Sembrada directamente.',
    ...harvest(D1, 90, 120),
    updatedAt: D1,
  },
  {
    id: 'plant-007',
    name: 'Perejil',
    category: 'perejil',
    origin: 'siembra_directa',
    plantedAt: D1,
    heightCm: null,
    quantity: 1,
    bedNumber: 4,
    soilType: 'jardin_arcilloso',
    notes: 'Sembrado directamente. Germinación lenta (3-4 semanas).',
    ...harvest(D1, 70, 90),
    updatedAt: D1,
  },

  // ── Lote 2: plantado el 18 de abril ─────────────────────────────────────
  {
    id: 'plant-008',
    name: 'Pimiento italiano',
    category: 'pimiento',
    origin: 'comprada',
    plantedAt: D2,
    heightCm: 20,
    quantity: 4,
    bedNumber: 1,
    soilType: 'jardin_arcilloso',
    notes: '4 plantas de vivero, 20 cm al trasplante.',
    ...harvest(D2, 75, 100),
    updatedAt: D2,
  },
  {
    id: 'plant-009',
    name: 'Pimiento de Gernika',
    category: 'pimiento',
    origin: 'comprada',
    plantedAt: D2,
    heightCm: 20,
    quantity: 4,
    bedNumber: 1,
    soilType: 'jardin_arcilloso',
    notes: '4 plantas de pimiento de Gernika de vivero, 20 cm.',
    ...harvest(D2, 70, 95),
    updatedAt: D2,
  },
  {
    id: 'plant-010',
    name: 'Tomate cherry',
    category: 'tomate',
    origin: 'comprada',
    plantedAt: D2,
    heightCm: 15,
    quantity: 2,
    bedNumber: 1,
    soilType: 'jardin_arcilloso',
    notes: '2 plantas de tomate cherry de vivero, 15 cm.',
    ...harvest(D2, 65, 85),
    updatedAt: D2,
  },
  {
    id: 'plant-011',
    name: 'Lechuga',
    category: 'lechuga',
    origin: 'comprada',
    plantedAt: D2,
    heightCm: 5,
    quantity: 8,
    bedNumber: 4,
    soilType: 'jardin_arcilloso',
    notes: '8 plantas de lechuga de vivero, 5 cm.',
    ...harvest(D2, 40, 55),
    updatedAt: D2,
  },
  {
    id: 'plant-012',
    name: 'Puerro',
    category: 'puerro',
    origin: 'comprada',
    plantedAt: D2,
    heightCm: 25,
    quantity: 8,
    bedNumber: 3,
    soilType: 'jardin_arcilloso',
    notes: '8 plantas de puerro de vivero, 25 cm.',
    ...harvest(D2, 120, 150),
    updatedAt: D2,
  },
  {
    id: 'plant-013',
    name: 'Cebolla',
    category: 'cebolla',
    origin: 'comprada',
    plantedAt: D2,
    heightCm: 25,
    quantity: 8,
    bedNumber: 3,
    soilType: 'jardin_arcilloso',
    notes: '8 plantas de cebolla de vivero, 25 cm.',
    ...harvest(D2, 80, 100),
    updatedAt: D2,
  },
  {
    id: 'plant-014',
    name: 'Fresas (18 abr)',
    category: 'fresa',
    origin: 'comprada',
    plantedAt: D2,
    heightCm: 20,
    quantity: 2,
    bedNumber: 2,
    soilType: 'jardin_arcilloso',
    notes: '2 plantas de fresa de vivero, 20 cm.',
    ...harvest(D2, 45, 75),
    updatedAt: D2,
  },
];
