import { PlantCatalogEntry, Plant, PlantCategory } from './types';
import { addDays, format } from 'date-fns';

export const OPEN_METEO_URL =
  'https://api.open-meteo.com/v1/forecast?latitude=43.083&longitude=-2.406&current=temperature_2m,weathercode,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max&timezone=Europe/Madrid&forecast_days=7';

export const PLANT_CATALOG: Record<PlantCategory, PlantCatalogEntry> = {
  tomate: {
    category: 'tomate',
    displayName: 'Tomate',
    icon: '🍅',
    harvestDaysMin: 110,
    harvestDaysMax: 150,
    frostSensitive: true,
    minGerminationTempC: 18,
    wateringFrequencyDays: { dry: 2, normal: 3, wet: 5 },
    claySoilNotes:
      'Suelo arcilloso: asegúrate de un buen drenaje. Añade perlita o arena gruesa si hay encharcamiento.',
  },
  fresa: {
    category: 'fresa',
    displayName: 'Fresa',
    icon: '🍓',
    harvestDaysMin: 45,
    harvestDaysMax: 75,
    frostSensitive: false,
    minGerminationTempC: null,
    wateringFrequencyDays: { dry: 2, normal: 2, wet: 4 },
    claySoilNotes:
      'Suelo arcilloso: riesgo de pudrición de raíz. Planta en montículo elevado y evita el riego excesivo.',
  },
  ajo: {
    category: 'ajo',
    displayName: 'Ajo',
    icon: '🧄',
    harvestDaysMin: 90,
    harvestDaysMax: 120,
    frostSensitive: false,
    minGerminationTempC: 5,
    wateringFrequencyDays: { dry: 5, normal: 7, wet: 10 },
    claySoilNotes:
      'Suelo arcilloso: puede dificultar el desarrollo del bulbo. Afloja bien el suelo en profundidad antes de plantar.',
  },
  acelga: {
    category: 'acelga',
    displayName: 'Acelga',
    icon: '🥬',
    harvestDaysMin: 55,
    harvestDaysMax: 90,
    frostSensitive: false,
    minGerminationTempC: 10,
    wateringFrequencyDays: { dry: 2, normal: 3, wet: 5 },
    claySoilNotes: null,
  },
  zanahoria: {
    category: 'zanahoria',
    displayName: 'Zanahoria',
    icon: '🥕',
    harvestDaysMin: 90,
    harvestDaysMax: 120,
    frostSensitive: false,
    minGerminationTempC: 7,
    wateringFrequencyDays: { dry: 3, normal: 4, wet: 6 },
    claySoilNotes:
      'Suelo arcilloso: MUY IMPORTANTE aflojar el suelo al menos 30cm de profundidad. La arcilla causa zanahorias deformadas y bifurcadas.',
  },
  perejil: {
    category: 'perejil',
    displayName: 'Perejil',
    icon: '🌿',
    harvestDaysMin: 70,
    harvestDaysMax: 90,
    frostSensitive: false,
    minGerminationTempC: 10,
    wateringFrequencyDays: { dry: 2, normal: 3, wet: 5 },
    claySoilNotes: null,
  },
  otro: {
    category: 'otro',
    displayName: 'Otro',
    icon: '🌱',
    harvestDaysMin: 60,
    harvestDaysMax: 120,
    frostSensitive: false,
    minGerminationTempC: null,
    wateringFrequencyDays: { dry: 3, normal: 4, wet: 6 },
    claySoilNotes: null,
  },
};

const PLANTING_DATE = '2026-04-08';

function computeHarvest(daysMin: number, daysMax: number) {
  const base = new Date(PLANTING_DATE);
  return {
    start: format(addDays(base, daysMin), 'yyyy-MM-dd'),
    end: format(addDays(base, daysMax), 'yyyy-MM-dd'),
  };
}

export const INITIAL_PLANTS: Plant[] = [
  {
    id: 'plant-001',
    name: 'Tomate comprado',
    category: 'tomate',
    origin: 'comprada',
    plantedAt: PLANTING_DATE,
    heightCm: 20,
    bedNumber: 1,
    soilType: 'jardin_arcilloso',
    notes: 'Planta comprada en vivero, altura 20cm al trasplante.',
    harvestWindowStart: computeHarvest(110, 150).start,
    harvestWindowEnd: computeHarvest(110, 150).end,
    updatedAt: PLANTING_DATE,
  },
  {
    id: 'plant-002',
    name: 'Tomate germinado',
    category: 'tomate',
    origin: 'autogerminated',
    plantedAt: PLANTING_DATE,
    heightCm: 4,
    bedNumber: 1,
    soilType: 'jardin_arcilloso',
    notes: 'Planta germinada en casa, muy pequeña al trasplante (4cm).',
    harvestWindowStart: computeHarvest(130, 170).start,
    harvestWindowEnd: computeHarvest(130, 170).end,
    updatedAt: PLANTING_DATE,
  },
  {
    id: 'plant-003',
    name: 'Fresas compradas',
    category: 'fresa',
    origin: 'comprada',
    plantedAt: PLANTING_DATE,
    heightCm: 5,
    bedNumber: 2,
    soilType: 'jardin_arcilloso',
    notes: 'Plantas de fresa de vivero.',
    harvestWindowStart: computeHarvest(45, 75).start,
    harvestWindowEnd: computeHarvest(45, 75).end,
    updatedAt: PLANTING_DATE,
  },
  {
    id: 'plant-004',
    name: 'Ajo germinado',
    category: 'ajo',
    origin: 'autogerminated',
    plantedAt: PLANTING_DATE,
    heightCm: 4,
    bedNumber: 2,
    soilType: 'jardin_arcilloso',
    notes: 'Diente de ajo germinado en casa.',
    harvestWindowStart: computeHarvest(90, 120).start,
    harvestWindowEnd: computeHarvest(90, 120).end,
    updatedAt: PLANTING_DATE,
  },
  {
    id: 'plant-005',
    name: 'Acelga',
    category: 'acelga',
    origin: 'siembra_directa',
    plantedAt: PLANTING_DATE,
    heightCm: null,
    bedNumber: 3,
    soilType: 'jardin_arcilloso',
    notes: 'Sembrada directamente.',
    harvestWindowStart: computeHarvest(55, 90).start,
    harvestWindowEnd: computeHarvest(55, 90).end,
    updatedAt: PLANTING_DATE,
  },
  {
    id: 'plant-006',
    name: 'Zanahoria',
    category: 'zanahoria',
    origin: 'siembra_directa',
    plantedAt: PLANTING_DATE,
    heightCm: null,
    bedNumber: 3,
    soilType: 'jardin_arcilloso',
    notes: 'Sembrada directamente.',
    harvestWindowStart: computeHarvest(90, 120).start,
    harvestWindowEnd: computeHarvest(90, 120).end,
    updatedAt: PLANTING_DATE,
  },
  {
    id: 'plant-007',
    name: 'Perejil',
    category: 'perejil',
    origin: 'siembra_directa',
    plantedAt: PLANTING_DATE,
    heightCm: null,
    bedNumber: 4,
    soilType: 'jardin_arcilloso',
    notes: 'Sembrado directamente. Germinación lenta (3-4 semanas).',
    harvestWindowStart: computeHarvest(70, 90).start,
    harvestWindowEnd: computeHarvest(70, 90).end,
    updatedAt: PLANTING_DATE,
  },
];
